import torch

manifest = {
    "manifest_version": 1,
    "device_name": "auto",
    "backend_import": None,
    "supported_dtypes": {
        torch.float32: True,
        torch.int64: True,
        torch.bool: True,
    },
    "device_count": 1,
    "hardware": {
        "memory_model": "discrete",
        "device_memory_gb": "auto",
        "system_memory_gb": "auto",
        "oom_recoverable": True,
    },
    "resource_limits": {
        "max_device_memory_mb": None,
        "max_system_memory_mb": None,
        "max_tensor_size_mb": None,
        "cleanup_threshold_pct": 80,
    },
    "capabilities": {
        "inference": True,
        "training": False,
        "serialization": False,
        "generator": False,
        "double_backward": False,
        "gradcheck": False,
        "gradient_checkpointing": False,
        "autocast": False,
        "fused_optimizer": False,
        "dataloader": False,
        "module_hooks": False,
        "channels_last": False,
        "sparse": False,
        "nested": False,
        "foreach": False,
        "fp8": False,
        "quantized": False,
        "compile": False,
        "pinned_memory": False,
        "streams": False,
        "events": False,
        "deterministic": False,
        "guard_alloc": False,
    },
    "skip_ops": [],
    "tolerance_overrides": {},
    "supported_container_formats": {},
    "custom_container_decoders": {},
    "reference_device": None,
    "custom_test_dirs": [],
}
